# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec66674eb441f0254d76a61d033e848ce5c0af71773b68e8a119c27f570a4a596d7644effb0a23a0b8c532caa87e5d306a970c2b0de48d9871e2d8ab5433bb2

test:
  secret_key_base: 94e39449d66cf84a3b19312bdcf2829a81857f224fb74ebafba964c5115feabf0e0bfc012069bf917911412aa7d82c846decb618067bf89cb7aa5b2e51a0dd7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
